name: Telegram Video Downloader Engine

on:
  repository_dispatch:
    types: [start_video_download]

jobs:
  process-video:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install yt-dlp requests
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Python Downloader
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ github.event.client_payload.chat_id }}
          URL: ${{ github.event.client_payload.url }}
          REPLY_TO: ${{ github.event.client_payload.reply_to }}
          WAIT_MSG_ID: ${{ github.event.client_payload.wait_msg_id }}
        run: python downloader.py


